import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/context/authContext";

import Header from "@/app/_components/Header";
import {ConvexClientProvider} from "@/app/ConvexClientProvider";
import {Toaster} from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ai-airer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (




            <html lang="en">
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased `}
              >
                  <ConvexClientProvider>
                      <AuthProvider>
                          <Toaster/>
                      <Header/>
                        {children}
                      </AuthProvider>

                  </ConvexClientProvider>

              </body>
            </html>



  );
}
